#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

mkdir -p reports/provenance

# 1) Freeze data/model/config hashes.
sha256sum \
  /data/Datasets/JSRT/splits.csv \
  /data/Datasets/JSRT/split_info.yaml \
  /data/Datasets/Montgomery/splits.csv \
  /data/Datasets/NIH_ChestXray14/raw/Data_Entry_2017.csv \
  configs/paths.yaml \
  configs/experiments.yaml \
  configs/counterfactuals.yaml \
  /data/models/jsrt_unet_baseline.pt \
  /data/models/montgomery_unet_baseline.pt \
  /data/models/shenzhen_unet_baseline.pt \
  /data/models/nih_unet_transfer.pt \
  /data/models/nih_mask_generator_isolated.pt \
  "$ROOT"/data/interim/jsrt/full/metadata.parquet \
  "$ROOT"/data/interim/montgomery/full/metadata.parquet \
  "$ROOT"/data/interim/shenzhen/full/metadata.parquet \
  "$ROOT"/data/interim/nih_chestxray14/full/metadata.parquet \
  > reports/provenance/phase0_hashes.sha256

# 2) Snapshot existing derived artifacts.
(
  find manuscript/tables -maxdepth 1 -type f -name 'table2_autogenerated.tex' -print
  find manuscript/figures -maxdepth 1 -type f -name '*.pdf' -print
  find manuscript/figures_png -maxdepth 1 -type f -name '*.png' -print 2>/dev/null || true
) | sort > reports/provenance/frozen_outputs_list_before.txt

if [ -s reports/provenance/frozen_outputs_list_before.txt ]; then
  sha256sum $(cat reports/provenance/frozen_outputs_list_before.txt) > reports/provenance/frozen_outputs_sha256_before.txt
else
  : > reports/provenance/frozen_outputs_sha256_before.txt
fi

# 3) Single regeneration pass from frozen artifacts.
python scripts/auto_fill_table2.py
python scripts/generate_publication_figures_final.py
python scripts/generate_final_png_figures.py

# 4) Post-run snapshot + diff.
(
  find manuscript/tables -maxdepth 1 -type f -name 'table2_autogenerated.tex' -print
  find manuscript/figures -maxdepth 1 -type f -name '*.pdf' -print
  find manuscript/figures_png -maxdepth 1 -type f -name '*.png' -print 2>/dev/null || true
) | sort > reports/provenance/frozen_outputs_list_after.txt

if [ -s reports/provenance/frozen_outputs_list_after.txt ]; then
  sha256sum $(cat reports/provenance/frozen_outputs_list_after.txt) > reports/provenance/frozen_outputs_sha256_after.txt
else
  : > reports/provenance/frozen_outputs_sha256_after.txt
fi

diff -u reports/provenance/frozen_outputs_sha256_before.txt reports/provenance/frozen_outputs_sha256_after.txt \
  > reports/provenance/frozen_outputs_diff.patch || true

echo "[phase0] complete"
